spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/binhvv5/configuration-repository
#          uri: file:///D://BINHVV//1_Project//MindE//configuration-repository
          skip-ssl-validation: true
server:
  port: 8888
